/* Auto-generated file by SVGR. Read WUIIcon/README.md */
import { IconProvider } from '../IconProvider';
import SvgArrowDownLeft from './ArrowDownLeft';
import SvgArrowDownRight from './ArrowDownRight';
import SvgArrowDown from './ArrowDown';
import SvgArrowRight from './ArrowRight';
import SvgArrowUpLeft from './ArrowUpLeft';
import SvgArrowUpRight from './ArrowUpRight';
import SvgArrowUp from './ArrowUp';
import SvgArrow from './Arrow';
import SvgArrowsMaximize from './ArrowsMaximize';
import SvgArrowsMinimize from './ArrowsMinimize';
import SvgAttach from './Attach';
import SvgAttention from './Attention';
import SvgAudio from './Audio';
import SvgAudioOff from './AudioOff';
import SvgB from './B';
import SvgBack from './Back';
import SvgBackward from './Backward';
import SvgBoard from './Board';
import SvgBrush from './Brush';
import SvgCalendar from './Calendar';
import SvgCamera2 from './Camera2';
import SvgCancelled from './Cancelled';
import SvgCard from './Card';
import SvgChangeIcon from './ChangeIcon';
import SvgChat from './Chat';
import SvgChat2 from './Chat2';
import SvgCheckCircle from './CheckCircle';
import SvgCheckCircleColor from './CheckCircleColor';
import SvgCheckingAccount from './CheckingAccount';
import SvgChevronDown from './ChevronDown';
import SvgChevronLeft from './ChevronLeft';
import SvgChevronRight from './ChevronRight';
import SvgChevronUp from './ChevronUp';
import SvgCircleImageBorder from './CircleImageBorder';
import SvgCircle from './Circle';
import SvgClock from './Clock';
import SvgClose from './Close';
import SvgCloud from './Cloud';
import SvgCollapse from './Collapse';
import SvgCopy1 from './Copy1';
import SvgCopy from './Copy';
import SvgCourses from './Courses';
import SvgDeparture from './Departure';
import SvgDeployOut from './DeployOut';
import SvgDeploy from './Deploy';
import SvgDoneCheck from './DoneCheck';
import SvgDone from './Done';
import SvgDownload from './Download';
import SvgDraggable from './Draggable';
import SvgDue from './Due';
import SvgEditBox from './EditBox';
import SvgEdit from './Edit';
import SvgEmail from './Email';
import SvgEmoji from './Emoji';
import SvgEmptyFolder from './EmptyFolder';
import SvgEntry from './Entry';
import SvgError from './Error';
import SvgExcerciseB from './ExcerciseB';
import SvgExercise from './Exercise';
import SvgExit1 from './Exit1';
import SvgExit from './Exit';
import SvgExpand from './Expand';
import SvgEyeOff from './EyeOff';
import SvgEye from './Eye';
import SvgFacebook from './Facebook';
import SvgFigures from './Figures';
import SvgFileImport from './FileImport';
import SvgFile1 from './File1';
import SvgFile from './File';
import SvgFilter2 from './Filter2';
import SvgFilter from './Filter';
import SvgFinished from './Finished';
import SvgFire from './Fire';
import SvgFolderAdd from './FolderAdd';
import SvgFolder from './Folder';
import SvgFolderCard from './FolderCard';
import SvgFolderCardHover from './FolderCardHover';
import SvgForward1 from './Forward1';
import SvgForward from './Forward';
import SvgFrame from './Frame';
import SvgFullClock from './FullClock';
import SvgGrid from './Grid';
import SvgGroup from './Group';
import SvgGroups from './Groups';
import SvgHand from './Hand';
import SvgHelp from './Help';
import SvgHome1 from './Home1';
import SvgHome from './Home';
import SvgIconPremiumLine from './IconPremiumLine';
import SvgIconPremium from './IconPremium';
import SvgImage from './Image';
import SvgImport from './Import';
import SvgInfo from './Info';
import SvgKnowledge from './Knowledge';
import SvgLayoutGrid from './LayoutGrid';
import SvgLightning from './Lightning';
import SvgLine from './Line';
import SvgLink from './Link';
import SvgListNumber from './ListNumber';
import SvgList from './List';
import SvgLock from './Lock';
import SvgLockOpen from './LockOpen';
import SvgLoudSpeaker from './LoudSpeaker';
import SvgMagicWand from './MagicWand';
import SvgMain2 from './Main2';
import SvgMeletoLogo from './MeletoLogo';
import SvgMeletoLogoText from './MeletoLogoText';
import SvgMenu from './Menu';
import SvgMessage from './Message';
import SvgMicrophoneOff from './MicrophoneOff';
import SvgMicrophone from './Microphone';
import SvgMicrophoneOffRed from './MicrophoneOffRed';
import SvgMicrophone16 from './Microphone16';
import SvgMinus1 from './Minus1';
import SvgMinus from './Minus';
import SvgMissed from './Missed';
import SvgNbase from './Nbase';
import SvgNewFrame from './NewFrame';
import SvgNote from './Note';
import SvgNotification from './Notification';
import SvgNounItalic from './NounItalic';
import SvgNoWifi from './NoWifi';
import SvgPaperclip from './Paperclip';
import SvgPaperList from './PaperList';
import SvgPausa from './Pausa';
import SvgPause from './Pause';
import SvgPayment from './Payment';
import SvgPaymentInfo from './PaymentInfo';
import SvgPdf from './Pdf';
import SvgPen from './Pen';
import SvgPhone from './Phone';
import SvgPhoto from './Photo';
import SvgPinOff from './PinOff';
import SvgPin from './Pin';
import SvgPlayerPlayBack from './PlayerPlayBack';
import SvgPlayerPlayForward from './PlayerPlayForward';
import SvgPlayerSkipBack from './PlayerSkipBack';
import SvgPlayerSkipForward from './PlayerSkipForward';
import SvgPlayFile from './PlayFile';
import SvgPlus from './Plus';
import SvgPointer from './Pointer';
import SvgPointsVertikal from './PointsVertikal';
import SvgPoints from './Points';
import SvgPrint from './Print';
import SvgPromo from './Promo';
import SvgReaction from './Reaction';
import SvgRecord from './Record';
import SvgRectRound from './RectRound';
import SvgRectSkew from './RectSkew';
import SvgRectangle from './Rectangle';
import SvgRegularLesson from './RegularLesson';
import SvgRepeat from './Repeat';
import SvgReply from './Reply';
import SvgReportAnalytics from './ReportAnalytics';
import SvgReport from './Report';
import SvgRhombus from './Rhombus';
import SvgSadSmile from './SadSmile';
import SvgScaleBigger from './ScaleBigger';
import SvgScaleSmaller from './ScaleSmaller';
import SvgSchool from './School';
import SvgScreenShare from './ScreenShare';
import SvgScreen from './Screen';
import SvgScreenshot from './Screenshot';
import SvgSearch from './Search';
import SvgSelectFilled from './SelectFilled';
import SvgSelect from './Select';
import SvgSend from './Send';
import SvgSettings from './Settings';
import SvgShareScreen from './ShareScreen';
import SvgSms from './Sms';
import SvgSortingRound from './SortingRound';
import SvgSorting from './Sorting';
import SvgSound from './Sound';
import SvgSpeakerphone from './Speakerphone';
import SvgSquare from './Square';
import SvgStar from './Star';
import SvgStar3 from './Star3';
import SvgStop from './Stop';
import SvgStopwatch from './Stopwatch';
import SvgStudents2 from './Students2';
import SvgSwipe from './Swipe';
import SvgSwitchCamera from './SwitchCamera';
import SvgT from './T';
import SvgTariff from './Tariff';
import SvgTariff1 from './Tariff1';
import SvgTariff2 from './Tariff2';
import SvgTeacher from './Teacher';
import SvgTeam from './Team';
import SvgText from './Text';
import SvgTiltShift from './TiltShift';
import SvgTools from './Tools';
import SvgTrash from './Trash';
import SvgTriangle from './Triangle';
import SvgTwitter from './Twitter';
import SvgTwoUsers from './TwoUsers';
import SvgU from './U';
import SvgUpload from './Upload';
import SvgUserB from './UserB';
import SvgUser from './User';
import SvgUserInvitation from './UserInvitation';
import SvgVideoCameraEye from './VideoCameraEye';
import SvgVideoCameraOff from './VideoCameraOff';
import SvgVideo from './Video';
import SvgVideoCamera from './VideoCamera';
import SvgVideoCameraOffRed from './VideoCameraOffRed';
import SvgWand from './Wand';
import SvgWifi from './Wifi';
import SvgWriting from './Writing';
export const ArrowDownLeftIcon = IconProvider(SvgArrowDownLeft, 'ArrowDownLeftIcon');
export const ArrowDownRightIcon = IconProvider(SvgArrowDownRight, 'ArrowDownRightIcon');
export const ArrowDownIcon = IconProvider(SvgArrowDown, 'ArrowDownIcon');
export const ArrowRightIcon = IconProvider(SvgArrowRight, 'ArrowRightIcon');
export const ArrowUpLeftIcon = IconProvider(SvgArrowUpLeft, 'ArrowUpLeftIcon');
export const ArrowUpRightIcon = IconProvider(SvgArrowUpRight, 'ArrowUpRightIcon');
export const ArrowUpIcon = IconProvider(SvgArrowUp, 'ArrowUpIcon');
export const ArrowIcon = IconProvider(SvgArrow, 'ArrowIcon');
export const ArrowsMaximizeIcon = IconProvider(SvgArrowsMaximize, 'ArrowsMaximizeIcon');
export const ArrowsMinimizeIcon = IconProvider(SvgArrowsMinimize, 'ArrowsMinimizeIcon');
export const AttachIcon = IconProvider(SvgAttach, 'AttachIcon');
export const AttentionIcon = IconProvider(SvgAttention, 'AttentionIcon');
export const AudioIcon = IconProvider(SvgAudio, 'AudioIcon');
export const AudioOffIcon = IconProvider(SvgAudioOff, 'AudioOffIcon');
export const BIcon = IconProvider(SvgB, 'BIcon');
export const BackIcon = IconProvider(SvgBack, 'BackIcon');
export const BackwardIcon = IconProvider(SvgBackward, 'BackwardIcon');
export const BoardIcon = IconProvider(SvgBoard, 'BoardIcon');
export const BrushIcon = IconProvider(SvgBrush, 'BrushIcon');
export const CalendarIcon = IconProvider(SvgCalendar, 'CalendarIcon');
export const Camera2Icon = IconProvider(SvgCamera2, 'Camera2Icon');
export const CancelledIcon = IconProvider(SvgCancelled, 'CancelledIcon');
export const CardIcon = IconProvider(SvgCard, 'CardIcon');
export const ChangeIconIcon = IconProvider(SvgChangeIcon, 'ChangeIconIcon');
export const ChatIcon = IconProvider(SvgChat, 'ChatIcon');
export const Chat2Icon = IconProvider(SvgChat2, 'Chat2Icon');
export const CheckCircleIcon = IconProvider(SvgCheckCircle, 'CheckCircleIcon');
export const CheckCircleColorIcon = IconProvider(SvgCheckCircleColor, 'CheckCircleColorIcon');
export const CheckingAccountIcon = IconProvider(SvgCheckingAccount, 'CheckingAccountIcon');
export const ChevronDownIcon = IconProvider(SvgChevronDown, 'ChevronDownIcon');
export const ChevronLeftIcon = IconProvider(SvgChevronLeft, 'ChevronLeftIcon');
export const ChevronRightIcon = IconProvider(SvgChevronRight, 'ChevronRightIcon');
export const ChevronUpIcon = IconProvider(SvgChevronUp, 'ChevronUpIcon');
export const CircleImageBorderIcon = IconProvider(SvgCircleImageBorder, 'CircleImageBorderIcon');
export const CircleIcon = IconProvider(SvgCircle, 'CircleIcon');
export const ClockIcon = IconProvider(SvgClock, 'ClockIcon');
export const CloseIcon = IconProvider(SvgClose, 'CloseIcon');
export const CloudIcon = IconProvider(SvgCloud, 'CloudIcon');
export const CollapseIcon = IconProvider(SvgCollapse, 'CollapseIcon');
export const Copy1Icon = IconProvider(SvgCopy1, 'Copy1Icon');
export const CopyIcon = IconProvider(SvgCopy, 'CopyIcon');
export const CoursesIcon = IconProvider(SvgCourses, 'CoursesIcon');
export const DepartureIcon = IconProvider(SvgDeparture, 'DepartureIcon');
export const DeployOutIcon = IconProvider(SvgDeployOut, 'DeployOutIcon');
export const DeployIcon = IconProvider(SvgDeploy, 'DeployIcon');
export const DoneCheckIcon = IconProvider(SvgDoneCheck, 'DoneCheckIcon');
export const DoneIcon = IconProvider(SvgDone, 'DoneIcon');
export const DownloadIcon = IconProvider(SvgDownload, 'DownloadIcon');
export const DraggableIcon = IconProvider(SvgDraggable, 'DraggableIcon');
export const DueIcon = IconProvider(SvgDue, 'DueIcon');
export const EditBoxIcon = IconProvider(SvgEditBox, 'EditBoxIcon');
export const EditIcon = IconProvider(SvgEdit, 'EditIcon');
export const EmailIcon = IconProvider(SvgEmail, 'EmailIcon');
export const EmojiIcon = IconProvider(SvgEmoji, 'EmojiIcon');
export const EmptyFolderIcon = IconProvider(SvgEmptyFolder, 'EmptyFolderIcon');
export const EntryIcon = IconProvider(SvgEntry, 'EntryIcon');
export const ErrorIcon = IconProvider(SvgError, 'ErrorIcon');
export const ExcerciseBIcon = IconProvider(SvgExcerciseB, 'ExcerciseBIcon');
export const ExerciseIcon = IconProvider(SvgExercise, 'ExerciseIcon');
export const Exit1Icon = IconProvider(SvgExit1, 'Exit1Icon');
export const ExitIcon = IconProvider(SvgExit, 'ExitIcon');
export const ExpandIcon = IconProvider(SvgExpand, 'ExpandIcon');
export const EyeOffIcon = IconProvider(SvgEyeOff, 'EyeOffIcon');
export const EyeIcon = IconProvider(SvgEye, 'EyeIcon');
export const FacebookIcon = IconProvider(SvgFacebook, 'FacebookIcon');
export const FiguresIcon = IconProvider(SvgFigures, 'FiguresIcon');
export const FileImportIcon = IconProvider(SvgFileImport, 'FileImportIcon');
export const File1Icon = IconProvider(SvgFile1, 'File1Icon');
export const FileIcon = IconProvider(SvgFile, 'FileIcon');
export const Filter2Icon = IconProvider(SvgFilter2, 'Filter2Icon');
export const FilterIcon = IconProvider(SvgFilter, 'FilterIcon');
export const FinishedIcon = IconProvider(SvgFinished, 'FinishedIcon');
export const FireIcon = IconProvider(SvgFire, 'FireIcon');
export const FolderAddIcon = IconProvider(SvgFolderAdd, 'FolderAddIcon');
export const FolderIcon = IconProvider(SvgFolder, 'FolderIcon');
export const FolderCardIcon = IconProvider(SvgFolderCard, 'FolderCardIcon');
export const FolderCardHoverIcon = IconProvider(SvgFolderCardHover, 'FolderCardHoverIcon');
export const Forward1Icon = IconProvider(SvgForward1, 'Forward1Icon');
export const ForwardIcon = IconProvider(SvgForward, 'ForwardIcon');
export const FrameIcon = IconProvider(SvgFrame, 'FrameIcon');
export const FullClockIcon = IconProvider(SvgFullClock, 'FullClockIcon');
export const GridIcon = IconProvider(SvgGrid, 'GridIcon');
export const GroupIcon = IconProvider(SvgGroup, 'GroupIcon');
export const GroupsIcon = IconProvider(SvgGroups, 'GroupsIcon');
export const HandIcon = IconProvider(SvgHand, 'HandIcon');
export const HelpIcon = IconProvider(SvgHelp, 'HelpIcon');
export const Home1Icon = IconProvider(SvgHome1, 'Home1Icon');
export const HomeIcon = IconProvider(SvgHome, 'HomeIcon');
export const IconPremiumLineIcon = IconProvider(SvgIconPremiumLine, 'IconPremiumLineIcon');
export const IconPremiumIcon = IconProvider(SvgIconPremium, 'IconPremiumIcon');
export const ImageIcon = IconProvider(SvgImage, 'ImageIcon');
export const ImportIcon = IconProvider(SvgImport, 'ImportIcon');
export const InfoIcon = IconProvider(SvgInfo, 'InfoIcon');
export const KnowledgeIcon = IconProvider(SvgKnowledge, 'KnowledgeIcon');
export const LayoutGridIcon = IconProvider(SvgLayoutGrid, 'LayoutGridIcon');
export const LightningIcon = IconProvider(SvgLightning, 'LightningIcon');
export const LineIcon = IconProvider(SvgLine, 'LineIcon');
export const LinkIcon = IconProvider(SvgLink, 'LinkIcon');
export const ListNumberIcon = IconProvider(SvgListNumber, 'ListNumberIcon');
export const ListIcon = IconProvider(SvgList, 'ListIcon');
export const LockIcon = IconProvider(SvgLock, 'LockIcon');
export const LockOpenIcon = IconProvider(SvgLockOpen, 'LockOpenIcon');
export const LoudSpeakerIcon = IconProvider(SvgLoudSpeaker, 'LoudSpeakerIcon');
export const MagicWandIcon = IconProvider(SvgMagicWand, 'MagicWandIcon');
export const Main2Icon = IconProvider(SvgMain2, 'Main2Icon');
export const MeletoLogoIcon = IconProvider(SvgMeletoLogo, 'MeletoLogoIcon');
export const MeletoLogoTextIcon = IconProvider(SvgMeletoLogoText, 'MeletoLogoTextIcon');
export const MenuIcon = IconProvider(SvgMenu, 'MenuIcon');
export const MessageIcon = IconProvider(SvgMessage, 'MessageIcon');
export const MicrophoneOffIcon = IconProvider(SvgMicrophoneOff, 'MicrophoneOffIcon');
export const MicrophoneIcon = IconProvider(SvgMicrophone, 'MicrophoneIcon');
export const MicrophoneOffRedIcon = IconProvider(SvgMicrophoneOffRed, 'MicrophoneOffRedIcon');
export const Microphone16Icon = IconProvider(SvgMicrophone16, 'Microphone16Icon');
export const Minus1Icon = IconProvider(SvgMinus1, 'Minus1Icon');
export const MinusIcon = IconProvider(SvgMinus, 'MinusIcon');
export const MissedIcon = IconProvider(SvgMissed, 'MissedIcon');
export const NbaseIcon = IconProvider(SvgNbase, 'NbaseIcon');
export const NewFrameIcon = IconProvider(SvgNewFrame, 'NewFrameIcon');
export const NoteIcon = IconProvider(SvgNote, 'NoteIcon');
export const NotificationIcon = IconProvider(SvgNotification, 'NotificationIcon');
export const NounItalicIcon = IconProvider(SvgNounItalic, 'NounItalicIcon');
export const NoWifiIcon = IconProvider(SvgNoWifi, 'NoWifiIcon');
export const PaperclipIcon = IconProvider(SvgPaperclip, 'PaperclipIcon');
export const PaperListIcon = IconProvider(SvgPaperList, 'PaperListIcon');
export const PausaIcon = IconProvider(SvgPausa, 'PausaIcon');
export const PauseIcon = IconProvider(SvgPause, 'PauseIcon');
export const PaymentIcon = IconProvider(SvgPayment, 'PaymentIcon');
export const PaymentInfoIcon = IconProvider(SvgPaymentInfo, 'PaymentInfoIcon');
export const PdfIcon = IconProvider(SvgPdf, 'PdfIcon');
export const PenIcon = IconProvider(SvgPen, 'PenIcon');
export const PhoneIcon = IconProvider(SvgPhone, 'PhoneIcon');
export const PhotoIcon = IconProvider(SvgPhoto, 'PhotoIcon');
export const PinOffIcon = IconProvider(SvgPinOff, 'PinOffIcon');
export const PinIcon = IconProvider(SvgPin, 'PinIcon');
export const PlayerPlayBackIcon = IconProvider(SvgPlayerPlayBack, 'PlayerPlayBackIcon');
export const PlayerPlayForwardIcon = IconProvider(SvgPlayerPlayForward, 'PlayerPlayForwardIcon');
export const PlayerSkipBackIcon = IconProvider(SvgPlayerSkipBack, 'PlayerSkipBackIcon');
export const PlayerSkipForwardIcon = IconProvider(SvgPlayerSkipForward, 'PlayerSkipForwardIcon');
export const PlayFileIcon = IconProvider(SvgPlayFile, 'PlayFileIcon');
export const PlusIcon = IconProvider(SvgPlus, 'PlusIcon');
export const PointerIcon = IconProvider(SvgPointer, 'PointerIcon');
export const PointsVertikalIcon = IconProvider(SvgPointsVertikal, 'PointsVertikalIcon');
export const PointsIcon = IconProvider(SvgPoints, 'PointsIcon');
export const PrintIcon = IconProvider(SvgPrint, 'PrintIcon');
export const PromoIcon = IconProvider(SvgPromo, 'PromoIcon');
export const ReactionIcon = IconProvider(SvgReaction, 'ReactionIcon');
export const RecordIcon = IconProvider(SvgRecord, 'RecordIcon');
export const RectRoundIcon = IconProvider(SvgRectRound, 'RectRoundIcon');
export const RectSkewIcon = IconProvider(SvgRectSkew, 'RectSkewIcon');
export const RectangleIcon = IconProvider(SvgRectangle, 'RectangleIcon');
export const RegularLessonIcon = IconProvider(SvgRegularLesson, 'RegularLessonIcon');
export const RepeatIcon = IconProvider(SvgRepeat, 'RepeatIcon');
export const ReplyIcon = IconProvider(SvgReply, 'ReplyIcon');
export const ReportAnalyticsIcon = IconProvider(SvgReportAnalytics, 'ReportAnalyticsIcon');
export const ReportIcon = IconProvider(SvgReport, 'ReportIcon');
export const RhombusIcon = IconProvider(SvgRhombus, 'RhombusIcon');
export const SadSmileIcon = IconProvider(SvgSadSmile, 'SadSmileIcon');
export const ScaleBiggerIcon = IconProvider(SvgScaleBigger, 'ScaleBiggerIcon');
export const ScaleSmallerIcon = IconProvider(SvgScaleSmaller, 'ScaleSmallerIcon');
export const SchoolIcon = IconProvider(SvgSchool, 'SchoolIcon');
export const ScreenShareIcon = IconProvider(SvgScreenShare, 'ScreenShareIcon');
export const ScreenIcon = IconProvider(SvgScreen, 'ScreenIcon');
export const ScreenshotIcon = IconProvider(SvgScreenshot, 'ScreenshotIcon');
export const SearchIcon = IconProvider(SvgSearch, 'SearchIcon');
export const SelectFilledIcon = IconProvider(SvgSelectFilled, 'SelectFilledIcon');
export const SelectIcon = IconProvider(SvgSelect, 'SelectIcon');
export const SendIcon = IconProvider(SvgSend, 'SendIcon');
export const SettingsIcon = IconProvider(SvgSettings, 'SettingsIcon');
export const ShareScreenIcon = IconProvider(SvgShareScreen, 'ShareScreenIcon');
export const SmsIcon = IconProvider(SvgSms, 'SmsIcon');
export const SortingRoundIcon = IconProvider(SvgSortingRound, 'SortingRoundIcon');
export const SortingIcon = IconProvider(SvgSorting, 'SortingIcon');
export const SoundIcon = IconProvider(SvgSound, 'SoundIcon');
export const SpeakerphoneIcon = IconProvider(SvgSpeakerphone, 'SpeakerphoneIcon');
export const SquareIcon = IconProvider(SvgSquare, 'SquareIcon');
export const StarIcon = IconProvider(SvgStar, 'StarIcon');
export const Star3Icon = IconProvider(SvgStar3, 'Star3Icon');
export const StopIcon = IconProvider(SvgStop, 'StopIcon');
export const StopwatchIcon = IconProvider(SvgStopwatch, 'StopwatchIcon');
export const Students2Icon = IconProvider(SvgStudents2, 'Students2Icon');
export const SwipeIcon = IconProvider(SvgSwipe, 'SwipeIcon');
export const SwitchCameraIcon = IconProvider(SvgSwitchCamera, 'SwitchCameraIcon');
export const TIcon = IconProvider(SvgT, 'TIcon');
export const TariffIcon = IconProvider(SvgTariff, 'TariffIcon');
export const Tariff1Icon = IconProvider(SvgTariff1, 'Tariff1Icon');
export const Tariff2Icon = IconProvider(SvgTariff2, 'Tariff2Icon');
export const TeacherIcon = IconProvider(SvgTeacher, 'TeacherIcon');
export const TeamIcon = IconProvider(SvgTeam, 'TeamIcon');
export const TextIcon = IconProvider(SvgText, 'TextIcon');
export const TiltShiftIcon = IconProvider(SvgTiltShift, 'TiltShiftIcon');
export const ToolsIcon = IconProvider(SvgTools, 'ToolsIcon');
export const TrashIcon = IconProvider(SvgTrash, 'TrashIcon');
export const TriangleIcon = IconProvider(SvgTriangle, 'TriangleIcon');
export const TwitterIcon = IconProvider(SvgTwitter, 'TwitterIcon');
export const TwoUsersIcon = IconProvider(SvgTwoUsers, 'TwoUsersIcon');
export const UIcon = IconProvider(SvgU, 'UIcon');
export const UploadIcon = IconProvider(SvgUpload, 'UploadIcon');
export const UserBIcon = IconProvider(SvgUserB, 'UserBIcon');
export const UserIcon = IconProvider(SvgUser, 'UserIcon');
export const UserInvitationIcon = IconProvider(SvgUserInvitation, 'UserInvitationIcon');
export const VideoCameraEyeIcon = IconProvider(SvgVideoCameraEye, 'VideoCameraEyeIcon');
export const VideoCameraOffIcon = IconProvider(SvgVideoCameraOff, 'VideoCameraOffIcon');
export const VideoIcon = IconProvider(SvgVideo, 'VideoIcon');
export const VideoCameraIcon = IconProvider(SvgVideoCamera, 'VideoCameraIcon');
export const VideoCameraOffRedIcon = IconProvider(SvgVideoCameraOffRed, 'VideoCameraOffRedIcon');
export const WandIcon = IconProvider(SvgWand, 'WandIcon');
export const WifiIcon = IconProvider(SvgWifi, 'WifiIcon');
export const WritingIcon = IconProvider(SvgWriting, 'WritingIcon');
